### ISSUE TITLE
Are all these babel plugins required?

### ISSUE THREAD

**Issue by prodigitalson** [Bartozzz/crawlerr#41]
Getting error below if I attempt to run the code from `examples/get_title.js` in my own file:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/username/crawler-test/node_modules/queue-promise/dist/index.js:7:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I do not have any of the babel modules queue-promise is trying to install, and none of those are listed as dependencies (aside from `dev-dependencies`) in either `crawlerr` or `queue-promise` package.json. Am I doing something wrong, or was this a build issue you didn't catch?

**Comment by Bartozzz** [comment]
I'll have a look at this, probably a build issue. Normally, it should work without any additional Babel packages. Can you tell me which Node version are you using?

**Comment by prodigitalson** [comment]
Thanks!

Node 8.11.3
NPM 5.6.0

**Comment by Bartozzz** [comment]
I've just published [v1.5.0 on npm](https://www.npmjs.com/package/crawlerr). You can install it by running the following command in your CLI:

```bash
$ npm install crawlerr@1.5.0
```

It should work perfectly on [_Node.js LTS_ (8.12)](https://nodejs.org/en/download/). I guess it will work just fine on _Node 8.11.3_ but I encourage you to upgrade your Node version to a long-term supported version. Please, let me know if the error persists.
